### ISSUE TITLE
could't find netem qdisc for iface: eth1

### ISSUE THREAD

**Issue by AODtorusan** [acooks/jittertrap#29]
I compiled jittertrap from git (rev 185dacd), but when I run the server it fails to start;

```
root@jittertrap:~/workspace/jittertrap# ./server/jt-server --resource_path html5-client/output/
Setting resource path to "html5-client/output/"
lwsts[3425]: jittertrap server
Using resource path "html5-client/output/"
lwsts[3425]: Initial logging level 7
lwsts[3425]: Libwebsockets version: 1.6.0 4939a70
lwsts[3425]: IPV6 not compiled in
lwsts[3425]: libev support not compiled in
lwsts[3425]:  Threads: 1 each 1024 fds
lwsts[3425]:  mem: platform fd map:  4096 bytes
lwsts[3425]:  mem: per-conn:          284 bytes + protocol rx buf
lwsts[3425]:  canonical_hostname = jittertrap
lwsts[3425]:  Compiled with OpenSSL support
lwsts[3425]:  Using non-SSL mode
lwsts[3425]: ERROR on binding to port 80 (-1 98)
lwsts[3425]: lws_context_destroy
creating new queue for 31 messages of 3000 bytes each
switching to iface: [eth1]
monitoring iface: [eth1]
get netem for iface: [eth1]
could't find netem qdisc for iface: eth1
couldn't get netem parameters.
iface: eth1
iface: eth0
iface: eth2
iface: br0
4 ifaces
iface: eth1
iface: eth0
iface: eth2
iface: br0
get netem for iface: [eth1]
could't find netem qdisc for iface: eth1
couldn't get netem parameters.
lwsts[3425]: libwebsocket init failed
pthread_setaffinity_np: Invalid argument
```

Any idea why it would fail to get the netem parameters ?

**Comment by acooks** [comment]
Thanks for checking out JitterTrap and for the bug report!

I see how the output is confusing and will improve that shortly, but the error that prevents jt-server from running occurred higher up in the output: "ERROR on binding to port 80 (-1 98)"

Is there something else running on port 80? Could you please try specifying a different listening port (--port NNNN).

**Comment by AODtorusan** [comment]
Right, I forgot nginx was still running.
After stopping nginx, jittertrap can bind on port 80, but it still fails retrieving the netem parameters;
```
...
lwsts[3414]:  Compiled with OpenSSL support
lwsts[3414]:  Using non-SSL mode
lwsts[3414]:  Listening on port 80
creating new queue for 31 messages of 3000 bytes each
switching to iface: [eth1]
monitoring iface: [eth1]
get netem for iface: [eth1]
could't find netem qdisc for iface: eth1
couldn't get netem parameters.
iface: eth1
iface: eth0
iface: eth2
iface: br0
4 ifaces
iface: eth1
iface: eth0
iface: eth2
iface: br0
get netem for iface: [eth1]
could't find netem qdisc for iface: eth1
couldn't get netem parameters.
pthread_setaffinity_np: Invalid argument
```

**Comment by acooks** [comment]
As I was saying before, the netem messages are confusing, but not indicative of a problem if it occurs during startup. It's simply an indication that the netem qdisc has not been loaded yet. Loading the qdisc is one potential fix - it clearly needs fixing.

I suspect that the "pthread_setaffinity_np: Invalid argument"  message indicated that there's only one processor in your system/vm (See #27 ). Is that true and if so, could you configure the vm with two cpus?

**Comment by acooks** [comment]
@AODtorusan, could you please try the latest commit from and let me know if the issue is resolved?

**Comment by AODtorusan** [comment]
I am running it in a physical machine with just a single CPU.
After recompiling, the server can be started, but as soon as a client connects, I get a segment fault;

```
lwsts[7633]:  Listening on port 80
creating new queue for 31 messages of 3000 bytes each
switching to iface: [eth1]
available ifaces:  eth1 eth0 eth2 br0
RT thread CPU affinity:  CPU0
lwsts[7633]: lws_reset_header_table: wsi 0x8554468
    get  = /
    host: = 192.168.90.4
    connection: = keep-alive
    http/1.1  = HTTP/1.1
    accept: = text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-encoding: = gzip, deflate
    accept-language: = en-US,en;q=0.5
    user-agent: = Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
lwsts[7633]: lws_reset_header_table: wsi 0x8554468
Segmentation fault
```
I've not done any unix based cpp debugging, but does it make sense to get some gdb info ?

**Comment by acooks** [comment]
It would help a lot if you can get a backtrace from gdb.

Any other info you can share that would allow me to setup a VM would be great.

It will be interesting to see how well things run on your single CPU machine. I've run it on a Raspberry Pi with Ethernet over USB before, with mixed results.

**Comment by AODtorusan** [comment]
Its and old VIA i386 CPU, so it probably wont beat any world records. Its just for playing around with.

I put cpuinfo, lspci and the gdb output in;
https://gist.github.com/AODtorusan/6de3fb306b850df00885

**Comment by acooks** [comment]
It looks like the crash is in the http connection reuse code. It could be in libwebsockets. The JT code is very similar to the the example code in the libwebsockets test server. I'll investigate and get back.

In the meantime, could you have a look at the libwebsockets-test-* apps and see whether they run or crash on your system? You can run it from the build directory of libwebsockets like this:
`bin/libwebsockets-test-server --port 7682 --resource_path share/libwebsockets-test-server/`

**Comment by AODtorusan** [comment]
I indeed seems to have been an issue with libwebsockets. I was using git version 4939a708f81c, and after updating the master branch to f9267170a3ee, recompiling, both the test server and jittertrap started working as expected.
