### ISSUE TITLE
Triage toptalk chart load rendering quirk [$100]

### ISSUE THREAD

**Issue by acooks** [acooks/jittertrap#36]
When opening http://demo.jittertrap.net, the toptalk chart renders incorrectly. Sometimes the curve drops below zero on the y-axis or look as if elements are rendered out of sequence. The attached example screenshots illustrate the issue:
![render-issue1](https://cloud.githubusercontent.com/assets/459959/24290467/cd3cde2a-10d0-11e7-8fbe-64e77ebf4501.png)
![render-issue2](https://cloud.githubusercontent.com/assets/459959/24290465/cd1afb3e-10d0-11e7-88eb-a505e7408c41.png)
![render-issue3](https://cloud.githubusercontent.com/assets/459959/24290466/cd1eec9e-10d0-11e7-8129-c069f2332427.png)

I have not been able to reproduce the issue when running on the local machine (connecting to localhost).

**Comment by m3ntalsp00n** [comment]
You might be able to close this.

I suspect this may have been fixed by my previous update as I've not seen this behaviour since then. Either in the new code to munge the data or the new d3 v4 library - either way.

**Comment by acooks** [comment]
I've merged the new d3 v4 into the demo branch, updated the demo site and agree that the render issue shown above is fixed.

However, before I close this and payout the bounty, I really need to have a better understanding of what caused the problem and why munging the data might've fixed it. Were you able to reproduce it locally?

**Comment by m3ntalsp00n** [comment]
Pfft, there's no payout for this one - it's a freebie from another issue.

Yeah to be honest I have no idea. Can reproduce it fairly consistently running it locally in a vm. If I get bored in the next few weeks I'll spin it up in a debugger and have a look.

It's running the same data so we know that's ok.
I wonder if it's got anything to do with the d3 stack, area or scale calls on first load? Maybe something funny was going on.

**Comment by acooks** [comment]
This issue has been fixed. There are still a few other chart rendering issues, but this one if fixed. Closing.
