### ISSUE TITLE
Write a blog post about jittertrap [$35]

### ISSUE THREAD

**Issue by acooks** [acooks/jittertrap#37]
Write a public blog post about Jittertrap. Points for...
* What is it?
* What is the problem to solve?
* Show screenshot

**Comment by acooks** [comment]
Thanks for the [blog post](https://stevegreeneblog.wordpress.com/2017/04/15/jittertrap-a-cool-new-linux-tool/) @sgreene570. I'm closing this issue; feel free to claim the bounty.

I've doubled the bounty, hoping that you'll expand on that post and include a screenshot of jittertrap in action (instead of a screenshot of the post on your blog). I'm not asking for a positive review, just a more detailed point of view, as you've done with your other posts.

**Comment by acooks** [comment]
Apparently Bountysource were happy to take the top-up payment from my paypal account, but it doesn't reflect on the Bountysource system. I'll get it sorted it out...

**Comment by acooks** [comment]
I've sorted out the issue with the bounty.

**Comment by acooks** [comment]
@sgreene570 deleted the blog. Nice.

**Comment by sgreene570** [comment]
Sorry about deleting the post. I recently re did my entire blog and felt that the post was not worded in my real voice. I will re post a new one and link here soon (currently on vac). Sorry again.

**Comment by sgreene570** [comment]
Sorry again. Here it is.
http://stevegreene.me/jekyll/update/2017/06/16/using-jittertrap.html
