### ISSUE TITLE
Create a distro package for Debian [$65]

### ISSUE THREAD

**Issue by acooks** [acooks/jittertrap#40]
There's a half-baked debian package in the source tree to use as a starting point.

Todo:
- Build a debian package
- Submit to debian upstream for inclusion
- Document and track the process in this github issue

**Comment by acooks** [comment]
@nemaniarjun, I see you commented on the Bountysource site. Please add comments here if you encounter problems.

**Comment by nemaniarjun** [comment]
@acooks When I try to run `jt-sever` it gives me the following error:
```
 > sudo jt-server
jt-server[19660]: ERROR on binding to port 80 (-1 98)
RT thread [jt-toptalk] priority [3] CPU affinity:  CPU0
jt-server[19660]: libwebsocket init failed
```
Is this because `libwebsockets6` is not installed? It is not in the official debian/ubuntu repository

**Comment by nemaniarjun** [comment]
Scrape that I got it working now. I am adding libwebsockets8 as a dependency.

**Comment by nemaniarjun** [comment]
@acooks I have create a `.deb` file. 
What are the next steps for this issue?
:grin:

**Comment by nemaniarjun** [comment]
@acooks I have create a `.deb` file. 
What are the next steps for this issue?
:grin:

**Comment by acooks** [comment]
That's good news!

As the issue description says, the idea is to submit a package to the debian project. There's plenty of documentation on how to achieve this, but it will take a bit of time and effort.

https://www.debian.org/doc/manuals/maint-guide/index.en.html
https://wiki.debian.org/Packaging

**Comment by sciamano** [comment]
just creating a package would be fine, but 65 only once is really **naive** if you want that someone brings it onto the the debian project. You do not just put it into debian repo and then disappear (nobody in debian likes and wants that), but then you also commit yourself to become the maintainer of the package for years meaning dealing with bugreports, debian policy updates, new upstream versions and so on

**Comment by acooks** [comment]
@sciamano, I think you're confused about how free software contributions work.

I'm acutely aware of how software packaging and maintenance works and how much time and commitment it requires. That is why this task is still on the todo list. I'm also perfectly content with the amount of time, expertise and money I've already contributed to this project.

If jittertrap is useful to you and you feel like contributing to it, that contribution would be welcome and I would endeavour to support and encourage that effort by answering questions, reviewing changes, helping fix bugs, etc. However, if you're only looking for the money and find no other value in the contribution, then I suggest you move along and not spend any more time on it.

**Comment by acooks** [comment]
Closed, because it's clear that bounties attract the wrong kind of attention and does not help achieve the goal.
